### ISSUE TITLE
Tracking issue for the initial prototype

### ISSUE THREAD

**Issue by LYZJU2019** [Shidowy/rafka#2]
- [ ] Define necessary traits for consumer, producer and storage
- [ ] Implement unit tests
- [ ] In-memory storage
- [ ] Single terminal producer and single terminal consumer
